name: Deploy Firebase Functions

on:
  push:
    branches:
      - main # Trigger the workflow when changes are pushed to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Ensure this matches your Node.js version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: firebase login:ci --no-localhost
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Install dependencies
        run: npm install
        working-directory: ./functions

      - name: Deploy to Firebase
        run: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
